
spring:
  cloud:
    gateway:
      routes:
        - id: controlTest
          uri: http://localhost:9090
          predicates:
            - Path=/control
          filters:
            - PrefixPath=/serviceA
        - id: gh_test
          uri: http://localhost:9090
          predicates:
            - Path=/partners/{partner}/home
          filters:
            - PrefixPath=/{partner}

